---
title: "Mission"
format: html
---

The research community has recently been facing what some call a “reproducibility crisis” – the failure of seemingly well-established results to replicate. At the same time, statisticians have been calling for a rethink of traditionally used approaches, such as thresholding of statistical quanti- ties and declarations of “statistical significance.” The Open Science movement brings together these various strands, emphasizing such principles as sharing of code, data, and research products (publications), as well as practices such as preregistration. Concurrently, the US government and US-based funding agencies (including NSF, NIH, and NASA) are moving towards requiring the sharing of data and other research outputs, since these are essentially supported by the public. In August 2022 the Office of Science and Technology Policy (OSTP) released a memo (the “Nelson Memo”) on ensuring free, immediate, and equitable access to federally funded research. The Nelson Memo calls on federal agencies to update their public access policies no later than Dec. 31 2025 to make “publications and their supporting data” freely available without embargo. In short, the landscape in the US – both rhetorically (around notions of resolving the crisis) and practically – is rapidly shifting. To meet the new requirements as outlined in the Nelson Memo researchers (and, more generally, universities and research institutions) are going to have to change modes of operation; a shift to open practices to at least some extent will be unavoidable at the individual as well as institutional levels, underscoring the need for a Center to coordinate faculty efforts, and to support and educate researchers. Notably, the European Union has already experienced the beginning of this shift.

To date, there are few formal university-based centers in the US that address these issues. The Center for Open Science (COS) is based in Charlottesville, VA, but is not affiliated with the University of Virginia (though its founder and director, Brian Nosek, is a faculty member at UVA). Stanford University and the University of California, Berkeley, both have centers that touch on aspects of Open Science and scientific transparency and reproducibility, but these are narrower in scope than what we propose here. In short, the creation of such a Center would put Penn State at the leading edge domestically, and enhance our research community’s ability not only to make a smooth transition to the new landscape, but also to be at the forefront of research and education in Open Science.

While it is possible to “contract out” some work, e.g. for creating a data management plan, or for making data publicly available, there is a cost to researchers for doing so, and to the university more generally. Existing resources – for example, help from the Library in writing a data management plan – are already at or near capacity, even without the new standards. Furthermore, there are “pockets” of PSU researchers exploring the Open Science landscape on their own. We think that a Center, which will serve as a node for interested faculty, postdocs, and students, will both address the challenges in scaling up for the practicalities of meeting the requirements outlined in the Nelson Memo, and create synergy in the community to enhance PSU’s reputation for cutting- edge, replicable, and rigorous research. Indeed, a strong and visible “in-house” infrastructure for data sharing, code verification, and other elements of Open Science practice will be a boon for Penn State researchers, who will not need to hire outside the institution for these services.

The Vision of the proposed Center is to promote Open Science principles and practices within the Penn State community and nationally. This entails transparency of methods and reporting of results; sharing of code and data; and sharing of research outputs. The movement towards Open Science is in part a reaction against the reproducibility crisis, as well as high-profile instances of research fraud. Openness and transparency are ways to enhance research robustness and replica- bility; though insufficient in and of themselves, they are key tools towards this goal. Researchers worldwide are embracing Open Science practice, though the United States somewhat lags the Eu- ropean Union in adoption of such practices. Our vision is to create a model of a university-based Open Science center, and to highlight for the research community the benefits of such an approach, while acknowledging the barriers and difficulties. Implementation of Open Science best practices locally will serve as an exemplar for other universities to follow. Through support of educational reforms, the Center and its members will be leaders in implementing open research principles and practices throughout higher-education. And scholarship on Open Science will help to guide the nation’s scientists who wish to incorporate these ideals into their own workflows. In short, the Center’s vision is to be a catalyst for change not just at Penn State, but nationally, and potentially beyond.

The Mission of the proposed Center is to make Penn State University a national leader in the field of Open Science through cutting-edge research; educational reform and training at all levels (undergraduate through faculty); support of faculty in incorporating Open Science requirements into their work (data sharing, code verification) and grant proposals (data management plans); and building a scholarly community to share resources and knowledge, leading to synergy across Penn State as a whole. Since Open Science and modern statistical inference (leading to replicable and rigorous research) represent shifts in practice, are threaded through the research pipeline, and continue to evolve with experience, training and support must also be ongoing. The Center will be a nexus of research, education, service, and outreach (see brief description of Cores): supporting and educating the Penn State research community, as well as conducting scholarly investigations of Open Science and its efficacy (“meta-science”). Initial members of the Center come from a variety of units around the University, and represent a range of roles and levels of seniority.
